name: Build GAUCHE and run unit tests.

on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"

  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/*"
      - "CHANGELOG.md"
      - "CONTRIBUTORS.md"
      - "CONTRIBUTING.md"
      - "imgs/"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up GAUCHE and install all dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .[all]
    - name: Test with pytest.
      run: |
        pytest tests/
