name: Code style checks

on: [push]

jobs:
  black:
    name: "Ensure black compliance"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install code style checking tools
        run: python -m pip install black

      - name: Run black
        run: black --check .

  isort:
    name: "Ensure imports are correctly sorted"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install code style checking tools
        run: python -m pip install isort

      - name: Run isort
        run: isort . --check-only
